language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t thepixelboy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thepixelboy/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: docker-react
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-323171934152'
  bucket_path: 'docker-react'
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
